name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: npm i
      - name: test and build
        run: |
          npm run test
          npm run test:e2e:ci
          npm run type-check
          npm run lint
          npm run build
        env:
          CI: true
          # A long secret value used to encrypt the session cookie
          AUTH0_SECRET: ${{ secrets.AUTH0_SECRET }}
          # The base url of your application
          AUTH0_BASE_URL: http://localhost:3000
          # The url of your Auth0 tenant domain
          AUTH0_ISSUER_BASE_URL: ${{ secrets.AUTH0_ISSUER_BASE_URL }}
          # Your Auth0 applications Client ID
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          # Your Auth0 applications Client Secret
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          #Cypress test user config
          CYPRESS_SHIPPER_EMAIL: ${{ secrets.CYPRESS_SHIPPER_EMAIL }}
          CYPRESS_SHIPPER_PASSWORD: ${{ secrets.CYPRESS_SHIPPER_PASSWORD }}
